# Make sure to set the Run Configuration Active profile to local when running the service locally
# and have a running postgres:18 on your machine
eureka.client.service-url.defaultZone=${EUREKA_DEFAULTZONE}
spring.datasource.url=${DATASOURCE_URL}
